### ISSUE TITLE
Request for a non draft release

### ISSUE THREAD

**Issue by aliprax** [opendatamesh-initiative/odm-specification-datastoreapi#5]
### Current Status
- **Available Version**: v1.0.0-DRAFT

### Description
We currently have a draft version (v1.0.0-DRAFT) available.
Official JSON schema is available only for draft version of 1.0.0.
The json schema for v1.0.0 is empty schemas/v1.0.0/schema.json

**Comment by andrea-gioia** [comment]
Closed by #6

**Comment by andrea-gioia** [comment]
Check release notes [here](https://github.com/opendatamesh-initiative/odm-specification-datastoreapi/releases/tag/v1.0.0)
